In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
data = './car.data'
car_data = pd.read_csv(data, header=None)

Check dimensions of dataset

In [ ]:

car_data.shape

(1728, 7)

In [ ]:
car_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

Clearing the Attributes

In [ ]:
category = {'vhigh':0,'high':1,'med':2,'low':3}
car_data[0] = car_data[0].map(category)
car_data[0].unique()

array([0, 1, 2, 3])

In [ ]:
car_data[1] = car_data[1].map(category)
car_data[1].unique()

array([0, 1, 2, 3])

In [ ]:
car_data[2] = car_data[2].map(lambda x: 5 if x=='5more' else (3 if x=='2' else (5 if x=='4' else int(x) )))
car_data[2].unique()

array([3, 5])

In [ ]:
car_data[3] = car_data[3].map(lambda x: 4 if(x=='more') else int(x) )
car_data[3].unique()

array([2, 4])

In [ ]:
category2 = {'small':0,'med':1,'big':2}
car_data[4] = car_data[4].map(category2)
car_data[4].unique()

array([0, 1, 2])

In [ ]:
category3 = {'low':0,'med':1,'high':2}
car_data[5] = car_data[5].map(category3)
car_data[5].unique()

array([0, 1, 2])

Change the column names

In [ ]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

car_data.columns = col_names
col_names

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

Check is there any null values

In [ ]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   int64 
 1   maint     1728 non-null   int64 
 2   doors     1728 non-null   int64 
 3   persons   1728 non-null   int64 
 4   lug_boot  1728 non-null   int64 
 5   safety    1728 non-null   int64 
 6   class     1728 non-null   object
dtypes: int64(6), object(1)
memory usage: 94.6+ KB


Declare feature vector and target variable

In [ ]:
X = car_data.drop(['class'], axis=1)
y = car_data['class']

In [ ]:
car_data

buying  maint  doors  persons  lug_boot  safety  class
0          0      0      3        2         0       0  unacc
1          0      0      3        2         0       1  unacc
2          0      0      3        2         0       2  unacc
3          0      0      3        2         1       0  unacc
4          0      0      3        2         1       1  unacc
...      ...    ...    ...      ...       ...     ...    ...
1723       3      3      5        4         1       1   good
1724       3      3      5        4         1       2  vgood
1725       3      3      5        4         2       0  unacc
1726       3      3      5        4         2       1   good
1727       3      3      5        4         2       2  vgood

[1728 rows x 7 columns]

Split data into separate training (70%) and test set(30%) with random_state=1

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

check the shape of X_train and X_test

In [ ]:
X_train.shape, X_test.shape

((1209, 6), (519, 6))

In [ ]:
X_train.head()

buying  maint  doors  persons  lug_boot  safety
1497       3      1      5        4         1       0
851        1      3      5        4         1       2
443        1      0      3        4         0       2
1631       3      3      3        4         0       2
1621       3      3      3        2         0       1

Random Forest Classifier model with parameter n_estimators=150 and random_state=1

In [ ]:
rfclassifier = RandomForestClassifier(n_estimators=150, random_state=1)


Model fitting

In [ ]:
rfclassifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=150, random_state=1)

Make Prediction

In [ ]:
y_prediction = rfclassifier.predict(X_test)

Check the Accuracy score 

In [ ]:
print('Accuracy score (with 150 decision-trees) : {0:0.4f}'. format(accuracy_score(y_test, y_prediction)))

Accuracy score (with 150 decision-trees) : 0.9615
